export const DATA_SOURCE = "DATA_SOURCE";
export const REDIS_CLIENT = "REDIS_CLIENT";
export const USER_REPOSITORY = "USER_REPOSITORY";
export const ROLE_REPOSITORY = "ROLE_REPOSITORY";
export const SCOOTER_REPOSITORY = "SCOOTER_REPOSITORY";
export const RENT_REPOSITORY = "RENT_REPOSITORY";
export const TASK_REPOSITORY = "TASK_REPOSITORY";
export const COMMENT_REPOSITORY = "COMMENT_REPOSITORY";
